- app/views/account/users/edit_profile.html.erb
- app/views/account/users/show_profile.html.erb
> User profile2

- app/controllers/account/answers_controller.rb
- app/controllers/account/questions_controller.rb
- app/controllers/answers_controller.rb
- app/controllers/questions_controller.rb
> modify return path

- app/controllers/welcome_controller.rb
- app/views/questions/index.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
- db/seeds.rb
把首页挪到welcome
加question 初始数据 seed.rd
> add question to seed.rb

- app/controllers/answers_controller.rb
- db/migrate/20160817033151_add_downpayment_to_question.rb
- db/schema.rb
> add_downpayment_to_question

- app/controllers/account/users_controller.rb
- app/views/account/users/_profile.html.erb
- db/migrate/20160817034527_add_balance_to_user.rb
- db/schema.rb
- db/seeds.rb
> User profile

- Gemfile
- Gemfile.lock
- app/controllers/account/questions_controller.rb
- app/controllers/answers_controller.rb
- app/controllers/questions_controller.rb
- app/models/question.rb
- app/models/user.rb
- app/views/account/questions/_form.html.erb
- app/views/account/questions/index.html.erb
- app/views/account/questions/show.html.erb
- app/views/questions/_form.html.erb
- app/views/questions/index.html.erb
- app/views/questions/show.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
- db/migrate/20160817052551_add_status_to_question.rb
- db/schema.rb
- db/seeds.rb
添加status字段
问问题扣款200
选择好问题打赏 把200 50分给平台，150分给回答者
> Question ask

- .gitignore
- app/assets/javascripts/admin/admins.coffee
- app/assets/stylesheets/admin/admins.scss
- app/controllers/admin/admins_controller.rb
- app/helpers/admin/admins_helper.rb
- app/views/admin/admins/questions_bill.html.erb
- app/views/admin/questions/index.html.erb
- config/routes.rb
- test/controllers/admin/admins_controller_test.rb
管理员能够看到有多少问题正在交易，有多少预付款正在流动，自己挣了多少抽成
> admin_bill

- db/migrate/20160817103634_change_column_question.rb
- db/schema.rb
> change_column_questions

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/questions.scss
- app/controllers/questions_controller.rb
- app/views/layouts/application.html.erb
- app/views/questions/_item.html.erb
- app/views/questions/_search_bar.html.erb
- app/views/questions/search.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
- db/seeds.rb
> Chenyl search question answerer

- app/assets/stylesheets/welcome_test.scss
- app/controllers/account/answers_controller.rb
- app/controllers/account/questions_controller.rb
- app/helpers/account/questions_helper.rb
- app/models/question.rb
- app/models/user.rb
- app/views/account/questions/index.html.erb
- app/views/welcome_test/_hot_question.html.erb
- app/views/welcome_test/_hot_question_section_title.html.erb
- config/routes.rb
add cancel and reopen
add balance greater than 0 in user model
> Dj0822 close question

- app/assets/stylesheets/application.scss
- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/welcome_controller.rb
- app/controllers/welcome_test_controller.rb
- app/models/question.rb
- app/models/question_invitation.rb
- app/models/user.rb
- app/services/reward_deposit_service.rb
- app/views/account/questions/_form.html.erb
- app/views/account/questions/invitated_questions.html.erb
- app/views/account/questions/show.html.erb
- app/views/common/_navbar.html.erb
- app/views/questions/_form.html.erb
- config/routes.rb
- db/migrate/20160822032352_create_question_invitation.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/question_invitations.yml
- test/models/question_invitation_test.rb
> Chenyl question invitation

- app/assets/javascripts/account/follows.coffee
- app/assets/stylesheets/account/follows.scss
- app/controllers/account/follows_controller.rb
- app/helpers/account/follows_helper.rb
- app/models/follow_relationship.rb
- app/models/user.rb
- app/views/account/users/_sidebar_exhibition.html.erb
- config/routes.rb
- db/migrate/20160822070850_create_follow_relationships.rb
- db/schema.rb
- test/controllers/account/follows_controller_test.rb
- test/fixtures/follow_relationships.yml
- test/models/follow_relationship_test.rb
> Dj0822 follower

- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/services/reward_deposit_service.rb
> modify service

- app/views/answers/new.html.erb
> add question in answer page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/welcome_test.scss
- app/views/common/_footer.html.erb
- app/views/common/_navbar.html.erb
> Dj0824 index3

- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/services/reward_best_answer.rb
- app/services/reward_deposit_service.rb
- app/views/account/questions/edit.html.erb
- app/views/account/questions/new.html.erb
- app/views/questions/_form.html.erb
- app/views/questions/_multiple_dropdown_bar.html.erb
1.提问时赏金由用户自己定义
2.同时修改平台分成 为 赏金的20%
> Chenyl alterable downpayment

- app/assets/stylesheets/account/users.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/welcome_test.scss
- app/controllers/account/users_controller.rb
- app/views/account/users/_profile.html.erb
- app/views/account/users/_user_center_navbar.html.erb
- app/views/account/users/_user_center_sidebar.html.erb
- app/views/account/users/index_profile.html.erb
- app/views/account/users/show_profile.html.erb
- app/views/common/_footer.html.erb
- app/views/common/_footer_index.html.erb
- app/views/layouts/user_center.html.erb
- app/views/layouts/welcome_test.html.erb
- config/initializers/assets.rb
- config/routes.rb
change footer
change user index page
> Dj0825 personnal index

- app/assets/stylesheets/account/users.scss
- app/assets/stylesheets/welcome_test.scss
- app/controllers/account/users_controller.rb
- app/views/account/users/_all_questions.html.erb
- app/views/account/users/_user_center_navbar.html.erb
- app/views/account/users/index_profile.html.erb
- app/views/account/users/show_profile.html.erb
> format the user center page

- app/assets/javascripts/application.js
- app/controllers/account/answers_controller.rb
- app/controllers/account/questions_controller.rb
- app/controllers/account/users_controller.rb
- app/controllers/notifications_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/welcome_test_controller.rb
- app/helpers/account/questions_helper.rb
- app/models/answer.rb
- app/models/question.rb
- app/services/notification_service.rb
- app/services/reward_best_answer.rb
- app/views/account/answers/index.html.erb
- app/views/account/answers/show.html.erb
- app/views/account/questions/index.html.erb
- app/views/account/questions/invitated_questions.html.erb
- app/views/notifications/answers/_notify_message_to_answer_owner.html.erb
- app/views/questions/_search_bar.html.erb
- app/views/questions/index.html.erb
- app/views/questions/show.html.erb
- app/views/welcome_test/_hot_question.html.erb
- db/seeds.rb
> fix page style

- app/controllers/account/follows_controller.rb
- app/controllers/account/users_controller.rb
- app/views/account/users/_profile_exhibition.html.erb
- app/views/account/users/exhibition_profile.html.erb
> add follower count and eye icon

- app/controllers/notifications_controller.rb
- app/controllers/welcome_test_controller.rb
- app/views/layouts/admin.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/profile.html.erb
- app/views/layouts/user_center.html.erb
> Chenyl add search

- app/assets/javascripts/application.js
- app/controllers/account/questions_controller.rb
- app/helpers/account/questions_helper.rb
- app/models/question.rb
- app/views/account/questions/index.html.erb
> only question haven't answered can be delete and cancel

- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/models/question.rb
- app/services/reward_deposit_service.rb
- app/views/questions/_multiple_dropdown_bar.html.erb
修复bug：
1.修改页面无法回显已邀请人
2.修改页面无法取消已邀请人
3.修改页面重复邀请已邀请人
4.修改页面没有trix_editor
> fix bug at multiple dropdown

- app/controllers/account/follows_controller.rb
- app/controllers/account/users_controller.rb
- app/views/account/users/_deposit_edit.html.erb
- app/views/account/users/_followees.html.erb
- app/views/account/users/_followers.html.erb
- app/views/account/users/_user_center_sidebar.html.erb
- app/views/account/users/_withdraw_edit.html.erb
- app/views/account/users/follow_show.html.erb
- app/views/account/users/replyers.html.erb
- app/views/account/users/wallet.html.erb
- config/routes.rb
- db/seeds.rb
> Dj0828 user center

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/welcome_test.scss
- app/controllers/account/users_controller.rb
- app/views/account/users/my_subscriptions.html.erb
- app/views/common/_admin_sidebar.html.erb
- app/views/questions/show.html.erb
- app/views/welcome_test/_picture_list.html.erb
> Liusining 0828 fix my subscriptions

- app/assets/stylesheets/answers.scss
- app/assets/stylesheets/application.scss
- app/views/answers/_question_info_sidebar.html.erb
- app/views/answers/new.html.erb
> add side bar

- app/assets/javascripts/admin/tags.coffee
- app/assets/stylesheets/admin/admins.scss
- app/assets/stylesheets/admin/tags.scss
- app/controllers/account/questions_controller.rb
- app/controllers/admin/tags_controller.rb
- app/helpers/admin/tags_helper.rb
- app/models/question.rb
- app/models/tag.rb
- app/models/tagging.rb
- app/views/admin/acts_as_taggable_on/tags/_tag.html.erb
- app/views/admin/questions/_question.html.erb
- app/views/admin/tags/_form.html.erb
- app/views/admin/tags/edit.html.erb
- app/views/admin/tags/index.html.erb
- app/views/admin/tags/new.html.erb
- app/views/admin/tags/show.html.erb
- app/views/common/_admin_sidebar.html.erb
- app/views/questions/_form.html.erb
- app/views/questions/_question.html.erb
- app/views/tags/show.html.erb
- config/routes.rb
> Chenyl tag

- app/assets/stylesheets/welcome_test.scss
- app/views/layouts/welcome_test.html.erb
- app/views/welcome_test/_bottom_banner.html.erb
- app/views/welcome_test/index.html.erb
> Dj0829 index

- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/models/tag.rb
- app/views/account/questions/_form.html.erb
- app/views/questions/_form.html.erb
- app/views/questions/_multiple_dropdown_bar.html.erb
> select tags when ask question

- app/controllers/account/answers_controller.rb
- app/controllers/account/questions_controller.rb
- app/controllers/account/users_controller.rb
- app/views/account/questions/invitated_questions.html.erb
- app/views/account/users/_user_center_right_sidebar.html.erb
- app/views/account/users/replyers.html.erb
- app/views/common/_navbar_index.html.erb
- app/views/questions/_form.html.erb
- app/views/questions/new.html.erb
> add sort to xueba plaza

- app/controllers/account/tags_controller.rb
- app/controllers/account/users_controller.rb
- app/controllers/guides_controller.rb
- app/views/account/tags/_hot_tags.html.erb
- app/views/account/tags/index.html.erb
- app/views/guides/replyers_guide.html.erb
- app/views/guides/tags_guide.html.erb
- app/views/layouts/guide.html.erb
- config/routes.rb
> Chenyl register guide

- app/assets/stylesheets/welcome_v1.scss
- app/views/account/users/_form.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/welcome_v1/_banner.html.erb
- app/views/welcome_v1/_question_list.html.erb
> change format

- app/controllers/account/answers_controller.rb
- app/controllers/account/questions_controller.rb
- app/controllers/questions_controller.rb
- app/helpers/account/users_helper.rb
- app/views/account/answers/new.html.erb
- app/views/account/users/_judge_subscription.html.erb
- app/views/account/users/my_subscriptions.html.erb
- app/views/questions/show.html.erb
> Liusining 0831 improve finish jump

- app/assets/javascripts/registrations.coffee
- app/assets/stylesheets/registrations.scss
- app/controllers/account/users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/welcome_v1_controller.rb
- app/helpers/registrations_helper.rb
- app/views/account/users/index_profile.html.erb
- config/routes.rb
> Liusining 0901 change devise

- app/assets/stylesheets/account/users.scss
- app/controllers/account/users_controller.rb
- app/views/account/users/index_profile.html.erb
> fix my achievement in index_profile

- app/views/account/users/index_profile.html.erb
- db/seeds.rb
> Liusining 0901 fix yihung suggestions

- app/assets/stylesheets/account/users.scss
- app/assets/stylesheets/application.scss
- app/views/account/users/_new_question.html.erb
- db/seeds.rb
> 支付宝和微信支付增加图标，并且以水平排列（原来是竖直方向上下排列）

- app/mailers/application_mailer.rb
- config/environments/production.rb
测试链接 https://sheltered-wildwood-83104.herokuapp.com
1) 发送邮件来自talent8.us@gmail.com 2)需要更新Heroku上sendgrid设置
> 问题回答邀请-发送邮件给邀请人

- app/assets/stylesheets/application.scss
- app/models/answer.rb
- app/views/layouts/admin.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/profile.html.erb
- app/views/layouts/user_center.html.erb
> Sticky footer
